### ISSUE TITLE
Incorrect components source path

### ISSUE THREAD

**Issue by teddybradford** [whoisryosuke/gatsby-documentation-starter#2]
When running the `gatsby develop` script on a fresh copy of this starter, the following error occurs:

```
The path passed to gatsby-source-filesystem does not exist on your file system:

../src/components/
```

Is the path supposed to be `./src/components/` (`./` instead of `../`)?

**Comment by whoisryosuke** [comment]
@teddybradford I designed this to work as a sub-repo inside of your project, such as a design system. Ideally, your project would be `project_name > src > components` and your docs would be `project_name > docs`.

You can [see an example of this in my design system boilerplate, under the Gatsby docs branch.](https://github.com/whoisryosuke/design-system-jss/tree/feat/docs-gatsby).

If you'd like to change the source/component path, [there's a section of the README that covers that](https://github.com/whoisryosuke/gatsby-documentation-starter#changing-source-folder) 👍

**Comment by teddybradford** [comment]
Ah, okay! I didn't realize the intent for this to be a sub-repo, so I wanted to make sure that wasn't a typo.
